name: 'St. Croix Sugar Beach, USVI'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.08245
title: St. Croix Sugar Beach
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfef8'
    - '#80aad0'
    - '#4f758c'
    - '#dacbb4'
    - '#4a4037'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0
  rhythmicContrast: 1
purpose: []
