name: stcroixsugarbeach
favicon: null
layout_spectrum: 0.11174830514937639
typography_spectrum: 0.8465422610752285
title: St. Croix Sugar Beach
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfef8'
    - '#80aad0'
    - '#4f758c'
    - '#dacbb4'
    - '#4a4037'
  brandStrength: 0.6208421045448631
  lightness: 0.7421242548152804
  saturation: 0.7711765873245895
  rhythmicContrast: 0.6855985140427947
purpose: []
